<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="4.0.0" />

    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    <PackageReference Include="QuestPDF" Version="2026.7.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GeradorDeProvas.Dominio\GeradorDeProvas.Dominio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Fonts/*.ttf" />
  </ItemGroup>

</Project>
